---
fake_backend_source_repo: "git@github.com:lusianneDjepang/fake-backend_for-sonar-projet.git"
fake_backend_source_branch: "master"
fake_backend_image_tag: "JenkinsCICDnew"

home: "/home/centos"
volume_database: "/srv/db-data"

ip_addr_preprod: "54.197.19.57"
ip_addr_prod: "3.92.49.186"
port_app: "8181"

# secret data vaulted
github_private_key: "{{vault_github_private_key}}"
docker_hub_login: "{{ vault_docker_hub_login }}"
docker_hub_email: "{{ vault_docker_hub_email }}"
docker_hub_password: "{{ vault_docker_hub_password }}"
